yolo5 deploy

diff --git a/.github/workflows/yolo5-deployment.yaml b/.github/workflows/yolo5-deployment.yaml
--- a/.github/workflows/yolo5-deployment.yaml
+++ b/.github/workflows/yolo5-deployment.yaml
@@ -24,6 +24,7 @@ jobs:
       run: |
         echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
         chmod 600 private_key.pem
+        
 
     - name: Set up Docker Build
       uses: docker/setup-buildx-action@v2
@@ -44,29 +45,33 @@ jobs:
       run: |
         INSTANCE_ID=$(aws autoscaling describe-auto-scaling-instances --query "AutoScalingInstances[0].InstanceId" --output text)
         echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
+      shell: bash
 
     - name: Get EC2 public IP
       id: get_public_ip
       run: |
         EC2_PUBLIC_IP=$(aws ec2 describe-instances --instance-ids ${{ env.INSTANCE_ID }} --query "Reservations[0].Instances[0].PublicIpAddress" --output text)
-        echo "EC2_PUBLIC_IP_ASG=$EC2_PUBLIC_IP_ASG" >> $GITHUB_ENV
+        echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP" >> $GITHUB_ENV
+        echo "Retrieved EC2 public IP: $EC2_PUBLIC_IP"
+      shell: bash
 
     - name: Deploy to AWS EC2
       run: |      
         # Retry SSH connection up to 5 times with a delay
         for attempt in {1..5}; do
           echo "Attempt $attempt to connect to ${{ env.EC2_PUBLIC_IP }}"
-          if ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ env.EC2_PUBLIC_IP_ASG }} "echo 'SSH connection successful'"; then
-            echo "SSH connection successful to ${{ env.EC2_PUBLIC_IP_ASG }}"
-            ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ env.EC2_PUBLIC_IP_ASG }} "sudo docker stop yolo5* || true"
-            ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ env.EC2_PUBLIC_IP_ASG }} "sudo docker rm yolo5* || true"
-            ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ env.EC2_PUBLIC_IP_ASG }} "sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/yolo5:latest"
-            ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ env.EC2_PUBLIC_IP_ASG }} "sudo docker run -d --name yolo5 ${{ secrets.DOCKERHUB_USERNAME }}/yolo5:latest"
+          if ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ env.EC2_PUBLIC_IP }} "echo 'SSH connection successful'"; then
+            echo "SSH connection successful to ${{ env.EC2_PUBLIC_IP }}"
+            ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ env.EC2_PUBLIC_IP }} "sudo docker stop yolo5* || true"
+            ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ env.EC2_PUBLIC_IP }} "sudo docker rm yolo5* || true"
+            ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ env.EC2_PUBLIC_IP }} "sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/yolo5:latest"
+            ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ env.EC2_PUBLIC_IP }} "sudo docker run -d --name yolo5 ${{ secrets.DOCKERHUB_USERNAME }}/yolo5:latest"
             break
           else
-            echo "SSH connection to ${{ env.EC2_PUBLIC_IP_ASG }} failed. Retrying in 10 seconds..."
+            echo "SSH connection to ${{ env.EC2_PUBLIC_IP }} failed. Retrying in 10 seconds..."
             sleep 10
           fi
         done
       env:
         AWS_REGION: ${{ secrets.AWS_REGION }}
+      shell: bash
