CI/CD # Debug SSH Connection

diff --git a/.github/workflows/yolo5-deployment.yaml b/.github/workflows/yolo5-deployment.yaml
--- a/.github/workflows/yolo5-deployment.yaml
+++ b/.github/workflows/yolo5-deployment.yaml
@@ -42,31 +42,31 @@ jobs:
 
     - name: Get EC2 instance ID
       run: |
-         INSTANCE_ID=$(aws autoscaling describe-auto-scaling-instances --query "AutoScalingInstances[0].InstanceId" --output text)
-          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
+        INSTANCE_ID=$(aws autoscaling describe-auto-scaling-instances --query "AutoScalingInstances[0].InstanceId" --output text)
+        echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
+
     - name: Get EC2 public IP
       id: get_public_ip
       run: |
         EC2_PUBLIC_IP=$(aws ec2 describe-instances --instance-ids ${{ env.INSTANCE_ID }} --query "Reservations[0].Instances[0].PublicIpAddress" --output text)
         echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP" >> $GITHUB_ENV
 
-    - name: Debug SSH Connection
-      run: |
-        ssh -v -i private_key.pem ubuntu@${{ env.EC2_PUBLIC_IP }} whoami
-      env:
-        EC2_PUBLIC_IP: ${{ env.EC2_PUBLIC_IP }}
-
-
     - name: Deploy to AWS EC2
-      uses: appleboy/ssh-action@master
-      with:
-        host: ${{ env.EC2_PUBLIC_IP}}
-        username: ubuntu
-        key: private_key.pem
-        script: |      
-          sudo docker pull '${{ secrets.DOCKERHUB_USERNAME }}/yolo5:latest'
-          sudo docker stop yolo5* || true
-          sudo docker rm yolo5* || true
-          sudo docker run -d --name yolo5 "${{ secrets.DOCKERHUB_USERNAME }}/yolo5:latest" | base64 -w 0
+      run: |      
+        # Retry SSH connection up to 5 times with a delay
+        for attempt in {1..5}; do
+          echo "Attempt $attempt to connect to ${{ env.EC2_PUBLIC_IP }}"
+          if ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ env.EC2_PUBLIC_IP }} "echo 'SSH connection successful'"; then
+            echo "SSH connection successful to ${{ env.EC2_PUBLIC_IP }}"
+            ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ env.EC2_PUBLIC_IP }} "sudo docker stop yolo5* || true"
+            ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ env.EC2_PUBLIC_IP }} "sudo docker rm yolo5* || true"
+            ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ env.EC2_PUBLIC_IP }} "sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/yolo5:latest"
+            ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ env.EC2_PUBLIC_IP }} "sudo docker run -d --name yolo5 ${{ secrets.DOCKERHUB_USERNAME }}/yolo5:latest"
+            break
+          else
+            echo "SSH connection to ${{ env.EC2_PUBLIC_IP }} failed. Retrying in 10 seconds..."
+            sleep 10
+          fi
+        done
       env:
         AWS_REGION: ${{ secrets.AWS_REGION }}
